config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  post "tasks", to: "tasks#create", as: :tasks_create
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to:"tasks#edit", as: :tasks_edit
  patch "tasks/:id", to:"tasks#update", as: :tasks_update
  delete "tasks/:id", to:"tasks#destroy", as: :tasks_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if @task.completed
      @status = "Completed"
    else
      @status = "Things to do"
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task=Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])

    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end



private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label "done" %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<ul>
  <h1>Things to do</h1>
  <% @tasks.each do |task| %>
  <li><%=link_to task.title, task_path(task.id) %></li>
  <%= link_to "EDIT", tasks_edit_path(task.id) %>
  <%= link_to "DELETE", tasks_delete_path(task.id),method: :delete %>
  <%end%>
</ul>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<p><%= @status %></p>

</p>



<%=link_to "back to the page", tasks_path %>